SELECT  DISTINCT ZONE,MPO_CARD_NO   FROM  SMART0005.dbo.ACC_LEDGER_Z_D_A, HRS_TRANS_WORK_ATTENDANCE_NEW  
WHERE ACC_LEDGER_Z_D_A.MPO_CARD_NO =HRS_TRANS_WORK_ATTENDANCE_NEW.EMP_CARD_NO
AND BRANCH_ID IN ('0001','0003') AND ZONE NOT IN ('ZH-Corporate Sales','X-MPO Accounts-Zone')

SELECT DISTINCT SMART0005.dbo.ACC_LEDGER_Z_D_A.ZONE,COUNT(ACC_LEDGER_Z_D_A.MPO_CARD_NO)TOTALMPO,  COUNT(HRS_TRANS_WORK_ATTENDANCE_NEW.ATTEN_TIMEIN) AS PRESENT
FROM            SMART0005.dbo.ACC_LEDGER_Z_D_A LEFT OUTER JOIN
                         HRS_TRANS_WORK_ATTENDANCE_NEW ON SMART0005.dbo.ACC_LEDGER_Z_D_A.MPO_CARD_NO = HRS_TRANS_WORK_ATTENDANCE_NEW.EMP_CARD_NO
WHERE        (SMART0005.dbo.ACC_LEDGER_Z_D_A.BRANCH_ID IN ('0001', '0003')) --AND HRS_TRANS_WORK_ATTENDANCE_NEW.ATTEN_STATUS='P'
GROUP BY SMART0005.dbo.ACC_LEDGER_Z_D_A.ZONE, SMART0005.dbo.ACC_LEDGER_Z_D_A.MPO_CARD_NO
HAVING        (NOT (SMART0005.dbo.ACC_LEDGER_Z_D_A.ZONE IN ('ZH-Corporate Sales', 'X-MPO Accounts-Zone'))) AND (COUNT(HRS_TRANS_WORK_ATTENDANCE_NEW.ATTEN_TIMEIN) IS NOT NULL)  


                       -- AND (SMART0005.dbo.ACC_LEDGER_Z_D_A.MPO_CARD_NO = 'M-12382')

ALTER VIEW TEST AS 
	SELECT ZONE,COUNT( MPO_CARD_NO) TOTALMPO,0 TOTALAREA,0 TOTALDIV,0 TOTALZH, 0 TOTALHEAD, 0 PRESENT, 0 ABSENT, 0 LEAVE,'MPO' TYPE FROM SMART0005.dbo.ACC_LEDGER_Z_D_A WHERE  BRANCH_ID IN ('0001','0003')
	AND ZONE NOT IN ('ZH-Corporate Sales','X-MPO Accounts-Zone')
	GROUP BY ZONE
	UNION ALL
	SELECT ZONE,0 TOTALMPO,COUNT( AREA ) TOTALAREA,0 TOTALDIV, 0 TOTALZH, 0 TOTALHEAD,0 PRESENT,0 ABSENT, 0 LEAVE,'AH' TYPE  FROM SMART0005.dbo.ACC_LEDGER_Z_D_A WHERE  BRANCH_ID IN ('0001','0003')
	AND ZONE NOT IN ('ZH-Corporate Sales','X-MPO Accounts-Zone')
	GROUP BY ZONE
	UNION ALL
	SELECT ZONE,0 TOTALMPO, 0 AREA,COUNT( DIVISION  ) TOTALDIV,0 TOTALZH, 0 TOTALHEAD,0 PRESENT,0 ABSENT, 0 LEAVE,'DH' TYPE FROM SMART0005.dbo.ACC_LEDGER_Z_D_A WHERE  BRANCH_ID IN ('0001','0003')
	AND ZONE NOT IN ('ZH-Corporate Sales','X-MPO Accounts-Zone')
	GROUP BY ZONE
	UNION ALL 
	SELECT ZONE,0 TOTALMPO, 0 AREA,0 TOTALDIV,0 TOTALZH, COUNT( BRANCH_ID  ) TOTALHEAD,0 PRESENT,0 ABSENT, 0 LEAVE,'Head' TYPE FROM SMART0005.dbo.ACC_LEDGER_Z_D_A WHERE  BRANCH_ID IN ('0001','0003')
	AND ZONE NOT IN ('ZH-Corporate Sales','X-MPO Accounts-Zone')
	GROUP BY ZONE
	UNION ALL
	SELECT ZONE,0 TOTALMPO, 0 AREA,0 TOTALDIV,COUNT( ZONE  ) TOTALZH, 0 TOTALHEAD,0 PRESENT,0 ABSENT, 0 LEAVE,'ZH' TYPE FROM SMART0005.dbo.ACC_LEDGER_Z_D_A WHERE  BRANCH_ID IN ('0001','0003')
	AND ZONE NOT IN ('ZH-Corporate Sales','X-MPO Accounts-Zone')
	GROUP BY ZONE
	UNION ALL
	

					  
	SELECT  SMART0005.dbo.ACC_LEDGER_Z_D_A.ZONE, 0 TOTALMPO, 0 AREA, 0 TOTALDIV, 0 TOTALHEAD, 0 TOTALZH, COUNT(HRS_TRANS_WORK_ATTENDANCE_NEW.ATTEN_TIMEIN) AS PRESENT, SUM(CASE WHEN HRS_TRANS_WORK_ATTENDANCE_NEW.ATTEN_STATUS = 'A' THEN 1 ELSE 0 END) AS ABSENT, SUM(CASE WHEN HRS_TRANS_WORK_ATTENDANCE_NEW.ATTEN_STATUS = 'L' THEN 1 ELSE 0 END) AS LEAVE,'MPO' TYPE
	FROM            SMART0005.dbo.ACC_LEDGER_Z_D_A LEFT OUTER JOIN
	HRS_TRANS_WORK_ATTENDANCE_NEW ON SMART0005.dbo.ACC_LEDGER_Z_D_A.MPO_CARD_NO = HRS_TRANS_WORK_ATTENDANCE_NEW.EMP_CARD_NO
	WHERE        (SMART0005.dbo.ACC_LEDGER_Z_D_A.BRANCH_ID IN ('0001', '0003')) --AND HRS_TRANS_WORK_ATTENDANCE_NEW.ATTEN_STATUS='P'
	GROUP BY SMART0005.dbo.ACC_LEDGER_Z_D_A.ZONE, SMART0005.dbo.ACC_LEDGER_Z_D_A.MPO_CARD_NO
	HAVING        (NOT (SMART0005.dbo.ACC_LEDGER_Z_D_A.ZONE IN ('ZH-Corporate Sales', 'X-MPO Accounts-Zone'))) AND (COUNT(HRS_TRANS_WORK_ATTENDANCE_NEW.ATTEN_TIMEIN) IS NOT NULL)  










	SELECT ZONE,SUM(TOTALMPO) TOTALMPO,SUM(TOTALAREA) AREA,SUM(TOTALDIV) TOTALDIV, SUM(TOTALHEAD) TOTALHEAD, SUM(TOTALZH) TOTALZH,SUM(PRESENT)PRESENT  FROM TEST,SMART0005.DBO.TEAM_CONFIG WHERE TEAM_CONFIG.ZONE_NAME=TEST.ZONE 
	GROUP BY ZONE

	SELECT TEAM_CONFIG.TEAM_NAME , ZONE,SUM(TOTALMPO) TOTALMPO,SUM(TOTALAREA) AREA,SUM(TOTALDIV) TOTALDIV,SUM(TOTALHEAD) TOTALHEAD, SUM(TOTALZH) TOTALZH,SUM(PRESENT)PRESENT, SUM(ABSENT)ABSENT, SUM(LEAVE)LEAVE  FROM TEST,SMART0005.DBO.TEAM_CONFIG WHERE TEAM_CONFIG.ZONE_NAME=TEST.ZONE 
	GROUP BY TEAM_CONFIG.TEAM_NAME,ZONE


	SELECT TEST.TYPE , SUM(TOTALMPO) TOTALMPO,SUM(TOTALAREA) AREA,SUM(TOTALDIV) TOTALDIV,SUM(TOTALHEAD) TOTALHEAD, SUM(TOTALZH) TOTALZH,SUM(PRESENT)PRESENT  FROM TEST,SMART0005.DBO.TEAM_CONFIG WHERE TEAM_CONFIG.ZONE_NAME=TEST.ZONE 
	GROUP BY TEST.TYPE










	SELECT 
    SMART0005.dbo.ACC_LEDGER_Z_D_A.ZONE, 
    0 AS TOTALMPO, 
    0 AS AREA, 
    0 AS TOTALDIV, 
    COUNT(HRS_TRANS_WORK_ATTENDANCE_NEW.ATTEN_TIMEIN) AS PRESENT, 
    SUM(CASE WHEN HRS_TRANS_WORK_ATTENDANCE_NEW.ATTEN_TIMEIN = 'A' THEN 1 ELSE 0 END) AS ABSENT,
    SUM(CASE WHEN HRS_TRANS_WORK_ATTENDANCE_NEW.ATTEN_TIMEIN = 'L' THEN 1 ELSE 0 END) AS LEAVE, 
    'MPO' AS TYPE 
FROM 
    SMART0005.dbo.ACC_LEDGER_Z_D_A 
LEFT OUTER JOIN 
    HRS_TRANS_WORK_ATTENDANCE_NEW ON SMART0005.dbo.ACC_LEDGER_Z_D_A.MPO_CARD_NO = HRS_TRANS_WORK_ATTENDANCE_NEW.EMP_CARD_NO
WHERE 
    (SMART0005.dbo.ACC_LEDGER_Z_D_A.BRANCH_ID IN ('0001', '0003')) 
   
GROUP BY 
    SMART0005.dbo.ACC_LEDGER_Z_D_A.ZONE, SMART0005.dbo.ACC_LEDGER_Z_D_A.MPO_CARD_NO
HAVING 
    (NOT (SMART0005.dbo.ACC_LEDGER_Z_D_A.ZONE IN ('ZH-Corporate Sales', 'X-MPO Accounts-Zone'))) 
    AND (COUNT(HRS_TRANS_WORK_ATTENDANCE_NEW.ATTEN_TIMEIN) IS NOT NULL)










	SELECT 
    TEAM_CONFIG.TEAM_NAME, 
    SUM(TEST.TOTALMPO) AS TOTALMPO, 
    SUM(TEST.TOTALAREA) AS AREA, 
    SUM(TEST.TOTALDIV) AS TOTALDIV, 
    SUM(TEST.TOTALHEAD) AS TOTALHEAD, 
    SUM(TEST.TOTALZH) AS TOTALZH,
    SUM(TEST.PRESENT) AS PRESENT, 
    SUM(TEST.ABSENT) AS ABSENT, 
    SUM(TEST.LEAVE) AS LEAVE 
FROM 
    TEST 
INNER JOIN 
    SMART0005.DBO.TEAM_CONFIG ON TEAM_CONFIG.ZONE_NAME = TEST.ZONE
GROUP BY 
    TEAM_CONFIG.TEAM_NAME;


	SELECT TEAM_CONFIG.TEAM_NAME , ZONE,SUM(TOTALMPO) TOTALMPO,SUM(TOTALAREA) AREA,SUM(TOTALDIV) TOTALDIV,SUM(TOTALHEAD) TOTALHEAD, SUM(TOTALZH) TOTALZH,
	SUM(PRESENT)PRESENT, SUM(ABSENT)ABSENT, SUM(LEAVE)LEAVE  FROM TEST,SMART0005.DBO.TEAM_CONFIG WHERE TEAM_CONFIG.ZONE_NAME=TEST.ZONE 
	GROUP BY TEAM_CONFIG.TEAM_NAME,ZONE

SELECT 
    ACC_LEDGER_Z_D_A.ZONE,
	TEAM_CONFIG.TEAM_NAME,
    COUNT(ACC_LEDGER_Z_D_A.MPO_CARD_NO) AS TOTAL_MPO,
    SUM(CASE WHEN HRS_TRANS_WORK_ATTENDANCE_NEW.ATTEN_STATUS = 'P' THEN 1 ELSE 0 END) AS PRESENT,
    SUM(CASE WHEN HRS_TRANS_WORK_ATTENDANCE_NEW.ATTEN_STATUS = 'A' THEN 1 ELSE 0 END) AS ABSENT,
    SUM(CASE WHEN HRS_TRANS_WORK_ATTENDANCE_NEW.ATTEN_STATUS = 'L' THEN 1 ELSE 0 END) AS LEAVE
FROM            
    SMART0005.dbo.ACC_LEDGER_Z_D_A 
LEFT OUTER JOIN
    HRS_TRANS_WORK_ATTENDANCE_NEW ON ACC_LEDGER_Z_D_A.MPO_CARD_NO = HRS_TRANS_WORK_ATTENDANCE_NEW.EMP_CARD_NO
LEFT OUTER JOIN
    SMART0005.dbo.TEAM_CONFIG ON ACC_LEDGER_Z_D_A.ZONE = TEAM_CONFIG.ZONE_NAME
WHERE        
    ACC_LEDGER_Z_D_A.BRANCH_ID IN ('0001', '0003')
    AND NOT (ACC_LEDGER_Z_D_A.ZONE IN ('ZH-Corporate Sales', 'X-MPO Accounts-Zone'))
GROUP BY 
    ACC_LEDGER_Z_D_A.ZONE,
	 TEAM_CONFIG.TEAM_NAME;

                      









SELECT 
    TEAM_CONFIG.ZONE_NAME,
    SUM(TEST.TOTALMPO) AS TOTALMPO, 
    SUM(TEST.TOTALAREA) AS AREA, 
    SUM(TEST.TOTALDIV) AS TOTALDIV, 
    SUM(TEST.TOTALHEAD) AS TOTALHEAD, 
    SUM(TEST.TOTALZH) AS TOTALZH,
    SUM(TEST.PRESENT) AS PRESENT, 
    SUM(TEST.ABSENT) AS ABSENT, 
    SUM(TEST.LEAVE) AS LEAVE 
FROM 
    TEST 
INNER JOIN 
    SMART0005.DBO.TEAM_CONFIG ON TEAM_CONFIG.ZONE_NAME = TEST.ZONE
GROUP BY 
    TEAM_CONFIG.ZONE_NAME;





	SELECT 
                TEAM_CONFIG.TEAM_NAME, 
                SUM(TEST.TOTALMPO) AS TOTALMPO, 
                SUM(TEST.TOTALAREA) AS AREA, 
                SUM(TEST.TOTALDIV) AS TOTALDIV, 
                SUM(TEST.TOTALHEAD) AS TOTALHEAD, 
                SUM(TEST.TOTALZH) AS TOTALZH,
                SUM(TEST.PRESENT) AS PRESENT, 
                SUM(TEST.ABSENT) AS ABSENT, 
                SUM(TEST.LEAVE) AS LEAVE 
            FROM 
                TEST 
            INNER JOIN 
                SMART0005.DBO.TEAM_CONFIG ON TEAM_CONFIG.ZONE_NAME = TEST.ZONE
            GROUP BY 
                TEAM_CONFIG.TEAM_NAME;

            SELECT 
                TEAM_CONFIG.ZONE_NAME,
                SUM(TEST.TOTALMPO) AS TOTALMPO, 
                SUM(TEST.TOTALAREA) AS AREA, 
                SUM(TEST.TOTALDIV) AS TOTALDIV, 
                SUM(TEST.TOTALHEAD) AS TOTALHEAD, 
                SUM(TEST.TOTALZH) AS TOTALZH,
                SUM(TEST.PRESENT) AS PRESENT, 
                SUM(TEST.ABSENT) AS ABSENT, 
                SUM(TEST.LEAVE) AS LEAVE 
            FROM 
                TEST 
            INNER JOIN 
                SMART0005.DBO.TEAM_CONFIG ON TEAM_CONFIG.ZONE_NAME = TEST.ZONE
            GROUP BY 
                TEAM_CONFIG.ZONE_NAME;








	SELECT TEAM_CONFIG.TEAM_NAME ,SMART0005.dbo.ACC_LEDGER_Z_D_A.ZONE, ZONE,SUM(TOTALMPO) TOTALMPO,SUM(TOTALAREA) AREA,SUM(TOTALDIV) TOTALDIV,SUM(TOTALHEAD) TOTALHEAD, SUM(TOTALZH) TOTALZH,
	SUM(PRESENT)PRESENT, SUM(ABSENT)ABSENT, SUM(LEAVE)LEAVE  FROM TEST,SMART0005.DBO.TEAM_CONFIG WHERE TEAM_CONFIG.ZONE_NAME=TEST.ZONE 
	GROUP BY TEAM_CONFIG.TEAM_NAME,ZONE 


	
SELECT 
    TEAM_CONFIG.TEAM_NAME,
   
    SUM(CASE WHEN TEST.TYPE = 'MPO' THEN TEST.TOTALMPO ELSE 0 END) AS TOTALMPO,
    SUM(CASE WHEN TEST.TYPE = 'AH' THEN TEST.TOTALAREA ELSE 0 END) AS AREA,
    SUM(CASE WHEN TEST.TYPE = 'DH' THEN TEST.TOTALDIV ELSE 0 END) AS TOTALDIV,
    SUM(CASE WHEN TEST.TYPE = 'Head' THEN TEST.TOTALHEAD ELSE 0 END) AS TOTALHEAD,
    SUM(CASE WHEN TEST.TYPE = 'ZH' THEN TEST.TOTALZH ELSE 0 END) AS TOTALZH
FROM 
    TEST
JOIN 
    SMART0005.dbo.TEAM_CONFIG ON TEAM_CONFIG.ZONE_NAME = TEST.ZONE
WHERE
    TEST.TYPE IN ('MPO', 'AH', 'DH', 'ZH', 'Head')
GROUP BY 
    TEAM_CONFIG.TEAM_NAME
  

	SELECT TYPE
FROM TEST
GROUP BY TYPE





SELECT 
    TEAM_CONFIG.TEAM_NAME,
    SUM(CASE WHEN TEST_TYPE.TYPE = 'MPO' THEN TEST.TOTALMPO ELSE 0 END) AS TOTALMPO,
    SUM(CASE WHEN TEST_TYPE.TYPE = 'AH' THEN TEST.TOTALAREA ELSE 0 END) AS AREA,
    SUM(CASE WHEN TEST_TYPE.TYPE = 'DH' THEN TEST.TOTALDIV ELSE 0 END) AS TOTALDIV,
    SUM(CASE WHEN TEST_TYPE.TYPE = 'Head' THEN TEST.TOTALHEAD ELSE 0 END) AS TOTALHEAD,
    SUM(CASE WHEN TEST_TYPE.TYPE = 'ZH' THEN TEST.TOTALZH ELSE 0 END) AS TOTALZH,
    TEST_TYPE.TYPE AS TYPE
FROM 
    SMART0005.dbo.TEAM_CONFIG
LEFT JOIN 
    TEST ON TEAM_CONFIG.ZONE_NAME = TEST.ZONE
LEFT JOIN 
    (SELECT DISTINCT TYPE FROM TEST) AS TEST_TYPE ON 1=1
WHERE
    TEST.TYPE IN ('MPO', 'AH', 'DH', 'ZH', 'Head')
GROUP BY 
    TEAM_CONFIG.TEAM_NAME, TEST_TYPE.TYPE;





SELECT 
    TEAM_CONFIG.ZONE_NAME,
    COUNT(ACC_LEDGER_Z_D_A.MPO_CARD_NO) AS TOTAL_MPO,
    SUM(CASE WHEN HRS_TRANS_WORK_ATTENDANCE_NEW.ATTEN_STATUS = 'P' THEN 1 ELSE 0 END) AS PRESENT,
    SUM(CASE WHEN HRS_TRANS_WORK_ATTENDANCE_NEW.ATTEN_STATUS = 'A' THEN 1 ELSE 0 END) AS ABSENT,
    SUM(CASE WHEN HRS_TRANS_WORK_ATTENDANCE_NEW.ATTEN_STATUS = 'L' THEN 1 ELSE 0 END) AS LEAVE
FROM            
    SMART0005.dbo.ACC_LEDGER_Z_D_A 
LEFT OUTER JOIN
    HRS_TRANS_WORK_ATTENDANCE_NEW ON ACC_LEDGER_Z_D_A.MPO_CARD_NO = HRS_TRANS_WORK_ATTENDANCE_NEW.EMP_CARD_NO
LEFT OUTER JOIN
    SMART0005.dbo.TEAM_CONFIG ON ACC_LEDGER_Z_D_A.ZONE = TEAM_CONFIG.ZONE_NAME
WHERE        
    ACC_LEDGER_Z_D_A.BRANCH_ID IN ('0001', '0003')
    AND NOT (TEAM_CONFIG.ZONE_NAME IN ('ZH-Corporate Sales', 'X-MPO Accounts-Zone'))
GROUP BY 
    TEAM_CONFIG.ZONE_NAME;


SELECT 
    ZONE_NAME,
    COUNT(*) AS TOTAL_ATTENDANCES,
    SUM(CASE WHEN ATTEN_STATUS = 'P' THEN 1 ELSE 0 END) AS PRESENT,
    SUM(CASE WHEN ATTEN_STATUS = 'A' THEN 1 ELSE 0 END) AS ABSENT,
    SUM(CASE WHEN ATTEN_STATUS = 'L' THEN 1 ELSE 0 END) AS LEAVE
FROM            
    HRS_TRANS_WORK_ATTENDANCE_NEW 
GROUP BY 
    ZONE_NAME;




SELECT ZONE, 0 TOTALMPO, 0 AS TOTALAREA, 0 AS TOTALDIV, 0 AS TOTALZH, 0 AS TOTALHEAD,COUNT(MPO_CARD_NO) AS PRESENT,0 AS ABSENT, 0 AS LEAVE, 'MPO' AS TYPE 
FROM SMART0005.dbo.ACC_LEDGER_Z_D_A,HRS_TRANS_WORK_ATTENDANCE_NEW  WHERE HRS_TRANS_WORK_ATTENDANCE_NEW.EMP_CARD_NO =ACC_LEDGER_Z_D_A.MPO_CARD_NO 
AND BRANCH_ID IN ('0001', '0003')
AND ZONE NOT IN ('ZH-Corporate Sales', 'X-MPO Accounts-Zone')
GROUP BY ZONE
UNION ALL
SELECT ZONE, 0 TOTALMPO, 0 AS TOTALAREA, 0 AS TOTALDIV, 0 AS TOTALZH, 0 AS TOTALHEAD,0 AS PRESENT,COUNT(MPO_CARD_NO) AS ABSENT, 0 AS LEAVE, 'MPO' AS TYPE 
FROM SMART0005.dbo.ACC_LEDGER_Z_D_A,HRS_TRANS_WORK_ATTENDANCE_NEW  WHERE HRS_TRANS_WORK_ATTENDANCE_NEW.EMP_CARD_NO =ACC_LEDGER_Z_D_A.MPO_CARD_NO 
AND BRANCH_ID IN ('0001', '0003')
AND ZONE NOT IN ('ZH-Corporate Sales', 'X-MPO Accounts-Zone')
GROUP BY ZONE
UNION ALL
SELECT ZONE, 0 TOTALMPO, 0 AS TOTALAREA, 0 AS TOTALDIV, 0 AS TOTALZH, 0 AS TOTALHEAD,0 PRESENT,0 AS ABSENT, COUNT(MPO_CARD_NO) AS LEAVE, 'MPO' AS TYPE 
FROM SMART0005.dbo.ACC_LEDGER_Z_D_A,HRS_TRANS_WORK_ATTENDANCE_NEW  WHERE HRS_TRANS_WORK_ATTENDANCE_NEW.EMP_CARD_NO =ACC_LEDGER_Z_D_A.MPO_CARD_NO 
AND BRANCH_ID IN ('0001', '0003')
AND ZONE NOT IN ('ZH-Corporate Sales', 'X-MPO Accounts-Zone')
GROUP BY ZONE





SELECT 
    ZONE,
    SUM(CASE WHEN HRS_TRANS_WORK_ATTENDANCE_NEW.ACTION = 'approve' THEN 1 ELSE 0 END) AS PRESENT,
    SUM(CASE WHEN HRS_TRANS_WORK_ATTENDANCE_NEW.ACTION = 'pending' THEN 1 ELSE 0 END) AS ABSENT,
    SUM(CASE WHEN HRS_TRANS_WORK_ATTENDANCE_NEW.ACTION = 'reject' OR HRS_TRANS_WORK_ATTENDANCE_NEW.ACTION = '' OR HRS_TRANS_WORK_ATTENDANCE_NEW.ACTION IS NULL THEN 1 ELSE 0 END) AS LEAVE,
    'MPO' AS TYPE 
FROM 
    SMART0005.dbo.ACC_LEDGER_Z_D_A
JOIN 
    HRS_TRANS_WORK_ATTENDANCE_NEW ON HRS_TRANS_WORK_ATTENDANCE_NEW.EMP_CARD_NO = ACC_LEDGER_Z_D_A.MPO_CARD_NO 
WHERE 
    ACC_LEDGER_Z_D_A.BRANCH_ID IN ('0001', '0003')
    AND ACC_LEDGER_Z_D_A.ZONE NOT IN ('ZH-Corporate Sales', 'X-MPO Accounts-Zone')
GROUP BY 
    ZONE
UNION ALL

SELECT ZONE, COUNT(MPO_CARD_NO) AS TOTALMPO, 0 AS TOTALAREA, 0 AS TOTALDIV, 0 AS TOTALZH, 0 AS TOTALHEAD, 0 AS PRESENT, 0 AS ABSENT, 0 AS LEAVE, 'MPO' AS TYPE 
FROM SMART0005.dbo.ACC_LEDGER_Z_D_A
WHERE BRANCH_ID IN ('0001', '0003')
AND ZONE NOT IN ('ZH-Corporate Sales', 'X-MPO Accounts-Zone')
GROUP BY ZONE
UNION ALL
SELECT ZONE, 0 AS TOTALMPO, COUNT(DISTINCT AREA) AS TOTALAREA, 0 AS TOTALDIV, 0 AS TOTALZH, 0 AS TOTALHEAD, 0 AS PRESENT, 0 AS ABSENT, 0 AS LEAVE, 'AH' AS TYPE 
FROM SMART0005.dbo.ACC_LEDGER_Z_D_A 
WHERE BRANCH_ID IN ('0001', '0003')
AND ZONE NOT IN ('ZH-Corporate Sales', 'X-MPO Accounts-Zone')
GROUP BY ZONE
UNION ALL
SELECT ZONE, 0 AS TOTALMPO, 0 AS TOTALAREA, COUNT(DISTINCT DIVISION) AS TOTALDIV, 0 AS TOTALZH, 0 AS TOTALHEAD, 0 AS PRESENT, 0 AS ABSENT, 0 AS LEAVE, 'DH' AS TYPE 
FROM SMART0005.dbo.ACC_LEDGER_Z_D_A 
WHERE BRANCH_ID IN ('0001', '0003')
AND ZONE NOT IN ('ZH-Corporate Sales', 'X-MPO Accounts-Zone')
GROUP BY ZONE
UNION ALL 
SELECT ZONE,0 TOTALMPO, 0 AREA,0 TOTALDIV,COUNT(DISTINCT ZONE  ) TOTALZH, 0 TOTALHEAD,0 PRESENT,0 ABSENT, 0 LEAVE,'ZH' TYPE FROM SMART0005.dbo.ACC_LEDGER_Z_D_A WHERE  BRANCH_ID IN ('0001','0003')
AND ZONE NOT IN ('ZH-Corporate Sales','X-MPO Accounts-Zone')
GROUP BY ZONE
UNION ALL 
SELECT ZONE,0 TOTALMPO, 0 AREA,0 TOTALDIV, 0 TOTALZH, COUNT( DISTINCT BRANCH_ID )TOTALHEAD ,0 PRESENT,0 ABSENT, 0 LEAVE,'ZH' TYPE FROM SMART0005.dbo.ACC_LEDGER_Z_D_A WHERE  BRANCH_ID IN ('0001','0003')
AND ZONE NOT IN ('ZH-Corporate Sales','X-MPO Accounts-Zone')
GROUP BY ZONE










	SELECT 
    ACC_LEDGER_Z_D_A.ZONE,
    TEAM_CONFIG.TEAM_NAME,
    COUNT(DISTINCT ACC_LEDGER_Z_D_A.MPO_CARD_NO) AS TOTAL_MPO,
    SUM(CASE WHEN HRS_TRANS_WORK_ATTENDANCE_NEW.ATTEN_STATUS = 'P' THEN 1 ELSE 0 END) AS PRESENT,
    SUM(CASE WHEN HRS_TRANS_WORK_ATTENDANCE_NEW.ATTEN_STATUS = 'A' THEN 1 ELSE 0 END) AS ABSENT,
    SUM(CASE WHEN HRS_TRANS_WORK_ATTENDANCE_NEW.ATTEN_STATUS = 'L' THEN 1 ELSE 0 END) AS LEAVE
FROM            
    SMART0005.dbo.ACC_LEDGER_Z_D_A 
LEFT OUTER JOIN
    HRS_TRANS_WORK_ATTENDANCE_NEW ON ACC_LEDGER_Z_D_A.MPO_CARD_NO = HRS_TRANS_WORK_ATTENDANCE_NEW.EMP_CARD_NO
LEFT OUTER JOIN
    SMART0005.dbo.TEAM_CONFIG ON ACC_LEDGER_Z_D_A.ZONE = TEAM_CONFIG.ZONE_NAME
WHERE        
    ACC_LEDGER_Z_D_A.BRANCH_ID IN ('0001', '0003')
    AND NOT (ACC_LEDGER_Z_D_A.ZONE IN ('ZH-Corporate Sales', 'X-MPO Accounts-Zone'))
GROUP BY 
    ACC_LEDGER_Z_D_A.ZONE,
    TEAM_CONFIG.TEAM_NAME;














	SELECT COUNT(*) AS Countt, COUNT(EMP_CARD_NO) AS EMP_CARD_NO, COUNT(USER_NAME) AS USER_NAME, ROLE, NULL AS TEAM_NAME, NULL AS TEAM_CODE
            FROM HRS_TRANS_WORK_ATTENDANCE_NEW 
            GROUP BY ROLE 
            HAVING COUNT(*) > 0 AND COUNT(EMP_CARD_NO) > 0 AND COUNT(USER_NAME) > 0 AND ROLE IS NOT NULL 
            UNION ALL 
            SELECT NULL, NULL, NULL, NULL, TEAM_NAME, TEAM_CODE
            FROM (SELECT DISTINCT TEAM_NAME, TEAM_CODE FROM SMART0005.dbo.TEAM_CONFIG) AS UniqueTeamNames 
            WHERE TEAM_NAME IS NOT NULL






SELECT 
    ZONE,
    NULL AS TEAM_NAME,
    COUNT(MPO_CARD_NO) AS TOTALMPO,
    COUNT(ATTEN_TIMEIN) AS PRESENT,
    NULL AS ABSENT,
    NULL AS LEAVE
FROM            
    SMART0005.dbo.ACC_LEDGER_Z_D_A 
LEFT OUTER JOIN
    HRS_TRANS_WORK_ATTENDANCE_NEW ON ACC_LEDGER_Z_D_A.MPO_CARD_NO = HRS_TRANS_WORK_ATTENDANCE_NEW.EMP_CARD_NO
WHERE        
    ACC_LEDGER_Z_D_A.BRANCH_ID IN ('0001', '0003')
    AND NOT (ACC_LEDGER_Z_D_A.ZONE IN ('ZH-Corporate Sales', 'X-MPO Accounts-Zone'))
GROUP BY 
    ZONE
HAVING        
    COUNT(ATTEN_TIMEIN) IS NOT NULL

UNION ALL 

SELECT 
    ACC_LEDGER_Z_D_A.ZONE,
    TEAM_CONFIG.TEAM_NAME,
    COUNT(DISTINCT ACC_LEDGER_Z_D_A.MPO_CARD_NO) AS TOTAL_MPO,
    SUM(CASE WHEN HRS_TRANS_WORK_ATTENDANCE_NEW.ATTEN_STATUS = 'P' THEN 1 ELSE 0 END) AS PRESENT,
    SUM(CASE WHEN HRS_TRANS_WORK_ATTENDANCE_NEW.ATTEN_STATUS = 'A' THEN 1 ELSE 0 END) AS ABSENT,
    SUM(CASE WHEN HRS_TRANS_WORK_ATTENDANCE_NEW.ATTEN_STATUS = 'L' THEN 1 ELSE 0 END) AS LEAVE
FROM            
    SMART0005.dbo.ACC_LEDGER_Z_D_A 
LEFT OUTER JOIN
    HRS_TRANS_WORK_ATTENDANCE_NEW ON ACC_LEDGER_Z_D_A.MPO_CARD_NO = HRS_TRANS_WORK_ATTENDANCE_NEW.EMP_CARD_NO
LEFT OUTER JOIN
    SMART0005.dbo.TEAM_CONFIG ON ACC_LEDGER_Z_D_A.ZONE = TEAM_CONFIG.ZONE_NAME
WHERE        
    ACC_LEDGER_Z_D_A.BRANCH_ID IN ('0001', '0003')
    AND NOT (ACC_LEDGER_Z_D_A.ZONE IN ('ZH-Corporate Sales', 'X-MPO Accounts-Zone'))
GROUP BY 
    ACC_LEDGER_Z_D_A.ZONE,
    TEAM_CONFIG.TEAM_NAME

UNION ALL 

SELECT 
    COUNT(*) AS Countt,
    COUNT(EMP_CARD_NO) AS EMP_CARD_NO,
    COUNT(USER_NAME) AS USER_NAME,
    ROLE,
    NULL AS TEAM_NAME,
    NULL AS TEAM_CODE
FROM 
    HRS_TRANS_WORK_ATTENDANCE_NEW 
GROUP BY 
    ROLE 
HAVING 
    COUNT(*) > 0 AND COUNT(EMP_CARD_NO) > 0 AND COUNT(USER_NAME) > 0 AND ROLE IS NOT NULL 

UNION ALL 

SELECT 
    NULL,
    NULL,
    NULL,
    NULL,
    TEAM_NAME,
    TEAM_CODE
FROM 
    (SELECT DISTINCT TEAM_NAME, TEAM_CODE FROM SMART0005.dbo.TEAM_CONFIG) AS UniqueTeamNames 
WHERE 
    TEAM_NAME IS NOT NULL;






SELECT 
    ZONE,
    NULL AS TEAM_NAME,
    COUNT(MPO_CARD_NO) AS TOTALMPO,
    COUNT(ATTEN_TIMEIN) AS PRESENT,
    NULL AS ABSENT,
    NULL AS LEAVE,
    NULL AS Countt,
    NULL AS EMP_CARD_NO,
    NULL AS USER_NAME,
    NULL AS ROLE,
    NULL AS TEAM_CODE
FROM            
    SMART0005.dbo.ACC_LEDGER_Z_D_A 
LEFT OUTER JOIN
    HRS_TRANS_WORK_ATTENDANCE_NEW ON ACC_LEDGER_Z_D_A.MPO_CARD_NO = HRS_TRANS_WORK_ATTENDANCE_NEW.EMP_CARD_NO
WHERE        
    ACC_LEDGER_Z_D_A.BRANCH_ID IN ('0001', '0003')
    AND NOT (ACC_LEDGER_Z_D_A.ZONE IN ('ZH-Corporate Sales', 'X-MPO Accounts-Zone'))
GROUP BY 
    ZONE

UNION ALL 

SELECT 
    ACC_LEDGER_Z_D_A.ZONE,
    TEAM_CONFIG.TEAM_NAME,
    COUNT(DISTINCT ACC_LEDGER_Z_D_A.MPO_CARD_NO) AS TOTAL_MPO,
    SUM(CASE WHEN HRS_TRANS_WORK_ATTENDANCE_NEW.ATTEN_STATUS = 'P' THEN 1 ELSE 0 END) AS PRESENT,
    SUM(CASE WHEN HRS_TRANS_WORK_ATTENDANCE_NEW.ATTEN_STATUS = 'A' THEN 1 ELSE 0 END) AS ABSENT,
    SUM(CASE WHEN HRS_TRANS_WORK_ATTENDANCE_NEW.ATTEN_STATUS = 'L' THEN 1 ELSE 0 END) AS LEAVE,
    NULL AS Countt,
    NULL AS EMP_CARD_NO,
    NULL AS USER_NAME,
    NULL AS ROLE,
    NULL AS TEAM_CODE
FROM            
    SMART0005.dbo.ACC_LEDGER_Z_D_A 
LEFT OUTER JOIN
    HRS_TRANS_WORK_ATTENDANCE_NEW ON ACC_LEDGER_Z_D_A.MPO_CARD_NO = HRS_TRANS_WORK_ATTENDANCE_NEW.EMP_CARD_NO
LEFT OUTER JOIN
    SMART0005.dbo.TEAM_CONFIG ON ACC_LEDGER_Z_D_A.ZONE = TEAM_CONFIG.ZONE_NAME
WHERE        
    ACC_LEDGER_Z_D_A.BRANCH_ID IN ('0001', '0003')
    AND NOT (ACC_LEDGER_Z_D_A.ZONE IN ('ZH-Corporate Sales', 'X-MPO Accounts-Zone'))
GROUP BY 
    ACC_LEDGER_Z_D_A.ZONE,
    TEAM_CONFIG.TEAM_NAME

UNION ALL 

SELECT 
    NULL AS ZONE,
    NULL AS TEAM_NAME,
    NULL AS TOTALMPO,
    NULL AS PRESENT,
    NULL AS ABSENT,
    NULL AS LEAVE,
    COUNT(*) AS Countt,
    COUNT(EMP_CARD_NO) AS EMP_CARD_NO,
    COUNT(USER_NAME) AS USER_NAME,
    ROLE,
    NULL AS TEAM_CODE
FROM 
    HRS_TRANS_WORK_ATTENDANCE_NEW 
GROUP BY 
    ROLE 
HAVING 
    COUNT(*) > 0 AND COUNT(EMP_CARD_NO) > 0 AND COUNT(USER_NAME) > 0 AND ROLE IS NOT NULL 

UNION ALL 

SELECT 
    NULL AS ZONE,
    TEAM_NAME,
    NULL AS TOTALMPO,
    NULL AS PRESENT,
    NULL AS ABSENT,
    NULL AS LEAVE,
    NULL AS Countt,
    NULL AS EMP_CARD_NO,
    NULL AS USER_NAME,
    NULL AS ROLE,
    TEAM_CODE
FROM 
    (SELECT DISTINCT TEAM_NAME, TEAM_CODE FROM SMART0005.dbo.TEAM_CONFIG) AS UniqueTeamNames 
WHERE 
    TEAM_NAME IS NOT NULL;









   

 







SELECT 
    ZONE,
    NULL AS TEAM_NAME,
    COUNT(DISTINCT MPO_CARD_NO) AS TOTALMPO,
    COUNT(DISTINCT ATTEN_TIMEIN) AS PRESENT,
    NULL AS ABSENT,
    NULL AS LEAVE,
    NULL AS Countt,
    NULL AS EMP_CARD_NO,
    NULL AS USER_NAME,
    NULL AS ROLE,
    NULL AS TEAM_CODE
FROM            
    SMART0005.dbo.ACC_LEDGER_Z_D_A 
LEFT OUTER JOIN
    HRS_TRANS_WORK_ATTENDANCE_NEW ON ACC_LEDGER_Z_D_A.MPO_CARD_NO = HRS_TRANS_WORK_ATTENDANCE_NEW.EMP_CARD_NO
WHERE        
    ACC_LEDGER_Z_D_A.BRANCH_ID IN ('0001', '0003')
    AND NOT (ACC_LEDGER_Z_D_A.ZONE IN ('ZH-Corporate Sales', 'X-MPO Accounts-Zone'))
GROUP BY 
    ZONE

UNION ALL 

SELECT 
    ACC_LEDGER_Z_D_A.ZONE,
    TEAM_CONFIG.TEAM_NAME,
    COUNT(DISTINCT ACC_LEDGER_Z_D_A.MPO_CARD_NO) AS TOTAL_MPO,
    SUM(CASE WHEN HRS_TRANS_WORK_ATTENDANCE_NEW.ATTEN_STATUS = 'P' THEN 1 ELSE 0 END) AS PRESENT,
    SUM(CASE WHEN HRS_TRANS_WORK_ATTENDANCE_NEW.ATTEN_STATUS = 'A' THEN 1 ELSE 0 END) AS ABSENT,
    SUM(CASE WHEN HRS_TRANS_WORK_ATTENDANCE_NEW.ATTEN_STATUS = 'L' THEN 1 ELSE 0 END) AS LEAVE,
    NULL AS Countt,
    NULL AS EMP_CARD_NO,
    NULL AS USER_NAME,
    NULL AS ROLE,
    NULL AS TEAM_CODE
FROM            
    SMART0005.dbo.ACC_LEDGER_Z_D_A 
LEFT OUTER JOIN
    HRS_TRANS_WORK_ATTENDANCE_NEW ON ACC_LEDGER_Z_D_A.MPO_CARD_NO = HRS_TRANS_WORK_ATTENDANCE_NEW.EMP_CARD_NO
LEFT OUTER JOIN
    SMART0005.dbo.TEAM_CONFIG ON ACC_LEDGER_Z_D_A.ZONE = TEAM_CONFIG.ZONE_NAME
WHERE        
    ACC_LEDGER_Z_D_A.BRANCH_ID IN ('0001', '0003')
    AND NOT (ACC_LEDGER_Z_D_A.ZONE IN ('ZH-Corporate Sales', 'X-MPO Accounts-Zone'))
GROUP BY 
    ACC_LEDGER_Z_D_A.ZONE,
    TEAM_CONFIG.TEAM_NAME

UNION ALL 

SELECT 
    NULL AS ZONE,
    NULL AS TEAM_NAME,
    NULL AS TOTALMPO,
    NULL AS PRESENT,
    NULL AS ABSENT,
    NULL AS LEAVE,
    COUNT(*) AS Countt,
    COUNT(DISTINCT EMP_CARD_NO) AS EMP_CARD_NO,
    COUNT(DISTINCT USER_NAME) AS USER_NAME,
    ROLE,
    NULL AS TEAM_CODE
FROM 
    HRS_TRANS_WORK_ATTENDANCE_NEW 
GROUP BY 
    ROLE 
HAVING 
    COUNT(*) > 0 AND COUNT(DISTINCT EMP_CARD_NO) > 0 AND COUNT(DISTINCT USER_NAME) > 0 AND ROLE IS NOT NULL 

UNION ALL 

SELECT 
    NULL AS ZONE,
    TEAM_NAME,
    NULL AS TOTALMPO,
    NULL AS PRESENT,
    NULL AS ABSENT,
    NULL AS LEAVE,
    NULL AS Countt,
    NULL AS EMP_CARD_NO,
    NULL AS USER_NAME,
    NULL AS ROLE,
    TEAM_CODE
FROM 
    (SELECT DISTINCT TEAM_NAME, TEAM_CODE FROM SMART0005.dbo.TEAM_CONFIG) AS UniqueTeamNames 
WHERE 
    TEAM_NAME IS NOT NULL;




	



SELECT 
    TEAM_CONFIG.TEAM_NAME, 
    TEST.ZONE,
    SUM(TEST.TOTALMPO) AS TOTALMPO,
    SUM(TEST.TOTALAREA) AS AREA,
    SUM(TEST.TOTALDIV) AS TOTALDIV,
    SUM(TEST.TOTALHEAD) AS TOTALHEAD,
    SUM(TEST.TOTALZH) AS TOTALZH,
    SUM(TEST.PRESENT) AS PRESENT,
    SUM(TEST.ABSENT) AS ABSENT,
    SUM(TEST.LEAVE) AS LEAVE,
    NULL AS Countt,
    NULL AS EMP_CARD_NO,
    NULL AS USER_NAME,
    NULL AS ROLE,
    NULL AS TEAM_CODE
FROM 
    TEST
INNER JOIN 
    SMART0005.dbo.TEAM_CONFIG 
ON 
    TEAM_CONFIG.ZONE_NAME = TEST.ZONE
GROUP BY 
    TEAM_CONFIG.TEAM_NAME, 
    TEST.ZONE

UNION ALL


SELECT 
    NULL AS TEAM_NAME,
    NULL AS ZONE,
    NULL AS TOTALMPO,
    NULL AS AREA,
    NULL AS TOTALDIV,
    NULL AS TOTALHEAD,
    NULL AS TOTALZH,
    NULL AS PRESENT,
    NULL AS ABSENT,
    NULL AS LEAVE,
    COUNT(*) AS Countt, 
    COUNT(EMP_CARD_NO) AS EMP_CARD_NO, 
    COUNT(USER_NAME) AS USER_NAME, 
    ROLE,
    NULL AS TEAM_CODE
FROM 
    HRS_TRANS_WORK_ATTENDANCE_NEW 
GROUP BY 
    ROLE 
HAVING 
    COUNT(*) > 0 
    AND COUNT(EMP_CARD_NO) > 0 
    AND COUNT(USER_NAME) > 0 
    AND ROLE IS NOT NULL 

UNION ALL

-- Selecting distinct TEAM_NAME and TEAM_CODE
SELECT 
    TEAM_NAME, 
    NULL AS ZONE,
    NULL AS TOTALMPO,
    NULL AS AREA,
    NULL AS TOTALDIV,
    NULL AS TOTALHEAD,
    NULL AS TOTALZH,
    NULL AS PRESENT,
    NULL AS ABSENT,
    NULL AS LEAVE,
    NULL AS Countt, 
    NULL AS EMP_CARD_NO, 
    NULL AS USER_NAME, 
    NULL AS ROLE,
    TEAM_CODE
FROM 
    (SELECT DISTINCT TEAM_NAME, TEAM_CODE FROM SMART0005.dbo.TEAM_CONFIG) AS UniqueTeamNames 
WHERE 
    TEAM_NAME IS NOT NULL












	SELECT ZONE, COUNT(MPO_CARD_NO) AS TOTALMPO, 0 AS TOTALAREA, 0 AS TOTALDIV, 0 AS TOTALZH, 0 AS TOTALHEAD, 0 AS PRESENT, 0 AS ABSENT, 0 AS LEAVE, 'MPO' AS TYPE 
FROM SMART0005.dbo.ACC_LEDGER_Z_D_A,HRS_TRANS_WORK_ATTENDANCE_NEW  WHERE HRS_TRANS_WORK_ATTENDANCE_NEW.EMP_CARD_NO =ACC_LEDGER_Z_D_A.MPO_CARD_NO 
AND BRANCH_ID IN ('0001', '0003')
AND ZONE NOT IN ('ZH-Corporate Sales', 'X-MPO Accounts-Zone')
GROUP BY ZONE
UNION ALL
SELECT ZONE, 0 AS TOTALMPO, COUNT(DISTINCT AREA) AS TOTALAREA, 0 AS TOTALDIV, 0 AS TOTALZH, 0 AS TOTALHEAD, 0 AS PRESENT, 0 AS ABSENT, 0 AS LEAVE, 'AH' AS TYPE 
FROM SMART0005.dbo.ACC_LEDGER_Z_D_A 
WHERE BRANCH_ID IN ('0001', '0003')
AND ZONE NOT IN ('ZH-Corporate Sales', 'X-MPO Accounts-Zone')
GROUP BY ZONE
UNION ALL
SELECT ZONE, 0 AS TOTALMPO, 0 AS TOTALAREA, COUNT(DISTINCT DIVISION) AS TOTALDIV, 0 AS TOTALZH, 0 AS TOTALHEAD, 0 AS PRESENT, 0 AS ABSENT, 0 AS LEAVE, 'DH' AS TYPE 
FROM SMART0005.dbo.ACC_LEDGER_Z_D_A 
WHERE BRANCH_ID IN ('0001', '0003')
AND ZONE NOT IN ('ZH-Corporate Sales', 'X-MPO Accounts-Zone')
GROUP BY ZONE
UNION ALL 
SELECT ZONE,0 TOTALMPO, 0 AREA,0 TOTALDIV,COUNT(DISTINCT ZONE  ) TOTALZH, 0 TOTALHEAD,0 PRESENT,0 ABSENT, 0 LEAVE,'ZH' TYPE FROM SMART0005.dbo.ACC_LEDGER_Z_D_A WHERE  BRANCH_ID IN ('0001','0003')
AND ZONE NOT IN ('ZH-Corporate Sales','X-MPO Accounts-Zone')
GROUP BY ZONE

UNION ALL (
	SELECT 
    ACC_LEDGER_Z_D_A.ZONE,
    TEAM_CONFIG.TEAM_NAME,
    COUNT(DISTINCT ACC_LEDGER_Z_D_A.MPO_CARD_NO) AS TOTAL_MPO,
    SUM(CASE WHEN HRS_TRANS_WORK_ATTENDANCE_NEW.ATTEN_STATUS = 'P' THEN 1 ELSE 0 END) AS PRESENT,
    SUM(CASE WHEN HRS_TRANS_WORK_ATTENDANCE_NEW.ATTEN_STATUS = 'A' THEN 1 ELSE 0 END) AS ABSENT,
    SUM(CASE WHEN HRS_TRANS_WORK_ATTENDANCE_NEW.ATTEN_STATUS = 'L' THEN 1 ELSE 0 END) AS LEAVE
FROM            
    SMART0005.dbo.ACC_LEDGER_Z_D_A 
LEFT OUTER JOIN
    HRS_TRANS_WORK_ATTENDANCE_NEW ON ACC_LEDGER_Z_D_A.MPO_CARD_NO = HRS_TRANS_WORK_ATTENDANCE_NEW.EMP_CARD_NO
LEFT OUTER JOIN
    SMART0005.dbo.TEAM_CONFIG ON ACC_LEDGER_Z_D_A.ZONE = TEAM_CONFIG.ZONE_NAME
WHERE        
    ACC_LEDGER_Z_D_A.BRANCH_ID IN ('0001', '0003')
    AND NOT (ACC_LEDGER_Z_D_A.ZONE IN ('ZH-Corporate Sales', 'X-MPO Accounts-Zone'))
GROUP BY 
    ACC_LEDGER_Z_D_A.ZONE,
    TEAM_CONFIG.TEAM_NAME
	)