
SELECT *FROM TEAM_CONFIG


select DISTINCT ACC_BRANCH.BRANCH_ID ,ACC_BRANCH.BRANCH_NAME 
from ACC_LEDGER_Z_D_A,ACC_BRANCH WHERE ACC_BRANCH.BRANCH_ID =ACC_LEDGER_Z_D_A.BRANCH_ID 


select DISTINCT TEAM_CONFIG.TEAM_NAME 
from ACC_LEDGER_Z_D_A,ACC_BRANCH,TEAM_CONFIG WHERE ACC_BRANCH.BRANCH_ID =ACC_LEDGER_Z_D_A.BRANCH_ID AND TEAM_CONFIG.ZONE_NAME=ACC_LEDGER_Z_D_A.ZONE
  AND ACC_BRANCH.BRANCH_ID='0001'

  
select DISTINCT ACC_LEDGER_Z_D_A.ZONE  
from ACC_LEDGER_Z_D_A,ACC_BRANCH,TEAM_CONFIG WHERE ACC_BRANCH.BRANCH_ID =ACC_LEDGER_Z_D_A.BRANCH_ID AND TEAM_CONFIG.ZONE_NAME=ACC_LEDGER_Z_D_A.ZONE
  AND ACC_BRANCH.BRANCH_ID='0001' AND TEAM_CONFIG.TEAM_NAME ='CHALLENGER'

  
select DISTINCT ACC_LEDGER_Z_D_A.DIVISION     
from ACC_LEDGER_Z_D_A,ACC_BRANCH,TEAM_CONFIG WHERE ACC_BRANCH.BRANCH_ID =ACC_LEDGER_Z_D_A.BRANCH_ID AND TEAM_CONFIG.ZONE_NAME=ACC_LEDGER_Z_D_A.ZONE
  AND ACC_BRANCH.BRANCH_ID='0001' AND TEAM_CONFIG.TEAM_NAME ='CHALLENGER' AND ACC_LEDGER_Z_D_A.ZONE ='NORTH ZONE'

  
select DISTINCT ACC_LEDGER_Z_D_A.DIVISION     
from ACC_LEDGER_Z_D_A,ACC_BRANCH,TEAM_CONFIG WHERE ACC_BRANCH.BRANCH_ID =ACC_LEDGER_Z_D_A.BRANCH_ID AND TEAM_CONFIG.ZONE_NAME=ACC_LEDGER_Z_D_A.ZONE
  AND ACC_BRANCH.BRANCH_ID='0001' AND TEAM_CONFIG.TEAM_NAME ='CHALLENGER' AND ACC_LEDGER_Z_D_A.ZONE ='NORTH ZONE'  
  AND ACC_LEDGER_Z_D_A.DIVISION  ='DH-DSM-Rezaul Karim-Bogura'

  
select DISTINCT ACC_LEDGER_Z_D_A.TERITORRY_CODE,ACC_LEDGER_Z_D_A.TERRITORRY_NAME      
from ACC_LEDGER_Z_D_A,ACC_BRANCH,TEAM_CONFIG WHERE ACC_BRANCH.BRANCH_ID =ACC_LEDGER_Z_D_A.BRANCH_ID AND TEAM_CONFIG.ZONE_NAME=ACC_LEDGER_Z_D_A.ZONE
  AND ACC_BRANCH.BRANCH_ID='0001' AND TEAM_CONFIG.TEAM_NAME ='CHALLENGER' AND ACC_LEDGER_Z_D_A.ZONE ='NORTH ZONE'  
  AND ACC_LEDGER_Z_D_A.DIVISION  ='DH-DSM-Rezaul Karim-Bogura'


  
select DISTINCT ACC_LEDGER_Z_D_A.ROUTE_NAME 
from ACC_LEDGER_Z_D_A,ACC_BRANCH,TEAM_CONFIG WHERE ACC_BRANCH.BRANCH_ID =ACC_LEDGER_Z_D_A.BRANCH_ID AND TEAM_CONFIG.ZONE_NAME=ACC_LEDGER_Z_D_A.ZONE
  AND ACC_BRANCH.BRANCH_ID='0001' AND TEAM_CONFIG.TEAM_NAME ='CHALLENGER' AND ACC_LEDGER_Z_D_A.ZONE ='NORTH ZONE'  
  AND ACC_LEDGER_Z_D_A.DIVISION  ='DH-DSM-Rezaul Karim-Bogura' AND ACC_LEDGER_Z_D_A.TERITORRY_CODE ='008'